### ISSUE TITLE
Monovariata Grafici

### ISSUE THREAD

**Issue by ghost** [datalifelab/corso-open-notebook-science#9]
Impostare posizione label costante

**Comment by ghost** [comment]
https://github.com/datalifelab/corso-open-notebook-science/blob/25b928e8c49b88e238cb0411076cf12a71f99f59/marradi.py#L112

**Comment by ghost** [comment]
risolto

**Comment by robertaturnu** [comment]
Grazie mille!!

Il giorno gio 25 ott 2018 alle 23:17 Scarselli Marco <
notifications@github.com> ha scritto:
